version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "rating:1:1"
    depends_on:
      - zookeeper
  redis:
    image: redis
  rating-calculator:
    build: ./rating-calculator
    depends_on:
      - zookeeper
      - kafka
      - redis
  data-collector:
    build: ./data-collector
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - redis
      - rating-calculator
