version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "rating:1:1"
    depends_on:
      - zookeeper
  redis:
    image: redis
    depends_on:
      - zookeeper
      - kafka
  rating-calculator:
    build: ./rating-calculator
    volumes:
      - ./calc-external.yml:/usr/lib/rating-calculator/config/application.yml
    depends_on:
      - zookeeper
      - kafka
      - redis
  data-collector:
    build: ./data-collector
    volumes:
      - /etc/data-external.yml:/usr/lib/data-collector/config/application.yml
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - redis
      - rating-calculator
